### ISSUE TITLE
Visual identity creation

### ISSUE THREAD

**Issue by SchmidtAugusto** [SchmidtAugusto/Fofanti-PlayStore#6]

**Comment by riklaus** [comment]
# font: Batayog Regular 
#color: #502273 (Purple)

**Comment by riklaus** [comment]
https://www.figma.com/file/2BzEceN4v7ETMWlSV6dyBs/Fofantti-Play-Store?type=design&node-id=0%3A1&t=zpQ0QyIB7m0sAzP6-1
